// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-6VpjGo01nPNycgKwpypi7TNT9U1_2Y',
    appId: '1:812810418234:web:52df8712468ff0db1e9d03',
    messagingSenderId: '812810418234',
    projectId: 'soruapp-31e3d',
    authDomain: 'soruapp-31e3d.firebaseapp.com',
    storageBucket: 'soruapp-31e3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEZC3H4jKEOL6_gvg02PzQcqpEYXw8Ls',
    appId: '1:812810418234:android:f6e0bb68c5b627161e9d03',
    messagingSenderId: '812810418234',
    projectId: 'soruapp-31e3d',
    storageBucket: 'soruapp-31e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvC09BhfwY0vnHjI4HFAshjAotlF9N7M',
    appId: '1:812810418234:ios:5adca7febfd736881e9d03',
    messagingSenderId: '812810418234',
    projectId: 'soruapp-31e3d',
    storageBucket: 'soruapp-31e3d.firebasestorage.app',
    iosBundleId: 'com.example.soruapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZvC09BhfwY0vnHjI4HFAshjAotlF9N7M',
    appId: '1:812810418234:ios:5adca7febfd736881e9d03',
    messagingSenderId: '812810418234',
    projectId: 'soruapp-31e3d',
    storageBucket: 'soruapp-31e3d.firebasestorage.app',
    iosBundleId: 'com.example.soruapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs-6VpjGo01nPNycgKwpypi7TNT9U1_2Y',
    appId: '1:812810418234:web:9e82eabc9850bf021e9d03',
    messagingSenderId: '812810418234',
    projectId: 'soruapp-31e3d',
    authDomain: 'soruapp-31e3d.firebaseapp.com',
    storageBucket: 'soruapp-31e3d.firebasestorage.app',
  );
}
